### ISSUE TITLE
Hi Noam please contuct us.

### ISSUE THREAD

**Issue by eladtenenbom** [noam7700/computer_graphics#3]
שלום נועם. אני מצאתי קריאה שלך בסטאק אוברפלו. הבנתי שאתה מתעסק קצת עם פפטיר ואוטומציות. 
אני מפתח בחברת סטארטאפ מנתניה. מפתחים מערכות תקיפה והגנה. 
מתמודד כרגע עם כמה מכשולים..
אשמח להחליף איתך כמה מילים לגבי העניין הזה ולשמוע איך התקדמת.. אלעד 0584000854

**Comment by noam7700** [comment]
פניתי אליך בהודעה
054-701-7860
